# Generated by Django 5.0.1 on 2024-02-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alquilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('mt2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='comprar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('mt2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tasar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('mt2', models.IntegerField()),
                ('ambientes', models.CharField(max_length=50)),
            ],
        ),
    ]
