# Generated by Django 5.0.1 on 2024-02-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquilar',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comprar',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
