# Generated by Django 5.0.1 on 2024-02-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_email_profile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
